services:
  postgres:
    container_name: postgres_identity
    image: postgres:16.3
    restart: no
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USERNAME}
    ports:
      - ${DB_PORT}:5432
  pgadmin:
    container_name: pgadmin_identity
    image: dpage/pgadmin4:8.8
    restart: no
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
      - PGADMIN_LISTEN_PORT=5050
    ports:
      - ${PGADMIN_PORT}:5050
    depends_on:
      - postgres
  redis:
    container_name: redis_identity
    image: redis/redis-stack
    restart: no
    ports:
      - ${RD_PORT}:6379
      - ${RD_STACK_PORT}:8001
  mail-dev:
    container_name: mail-dev_identity
    image: maildev/maildev
    restart: no
    ports:
      - ${MAIL_SERVER_PORT}:1080
      - ${MAIL_PORT}:1025